name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 7 * * *' # every day at 7:00 UTC
  workflow_dispatch: 

jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.WEBHOOK_URL }}