name: Trigger Netlify Build
on:
  schedule:
    - cron: '*/360 * * * *' # every 360 mins for 10 posts a day
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} secrets.WEBHOOK_URL